### PR TITLE
More Point methods + javadocs

### PR DESCRIPTION
**Pull request by Gulvan0**

### CODE REVIEW

**Comment by Gulvan0** [comment]
Indent was broken, I'll reopen a bit later

**Comment by ianharrigan** [comment]
OK, cool - since you are making changes, do you think we should change addend and subtrahend, etc? These arent very common names... its not an issue... just wondering what you think?

**Comment by Gulvan0** [comment]
> OK, cool - since you are making changes, do you think we should change addend and subtrahend, etc? These arent very common names... its not an issue... just wondering what you think?

Ok, but could you please specify the desired names?

**Comment by Gulvan0** [comment]
Somehow, I can't fix the indent :(

**Comment by ianharrigan** [comment]
I dunno, maybe just "value", "x", "y"? I mean, i think the function name already implies its meaning - that said, the names you have are certainly _more_ correct, and it doesnt _really_ matter - but these are terms that i hadnt personally heard of, or had forgotten or something (or my sister who is a mathematician! Well, she didnt remember hearing them either). Just food for thought really. I honestly dont have any actual issue with names - i just wonder if they might be confusing?

**Comment by ianharrigan** [comment]
> Somehow, I can't fix the indent :(

i can try, i (and haxeui) use spaces for tabs... once i merge it ill see if i can change it

**Pull request closed without merging**
