### PR TITLE
Internationalization support.

### PR DESCRIPTION
**Pull request by aW4KeNiNG**
Hi. I have been working on this new system to locate your apps in different languages.

You can download a full example here:

Spanish:
image

English:
image

Download code here: [feature_i18n.zip](https://github.com/haxeui/haxeui-core/files/1203069/feature_i18n.zip)

In the first place, we need to define the resource files in the `module.xml`:

```
<module id="main">
    <resources>
        <resource path="assets/locale" prefix="locale" />
    </resources>

    <locales>
        <locale id="en_US" resource="locale/en_US.properties"/>
        <locale id="es_ES" resource="locale/es_ES.properties"/>
    </locales>
</module>
```

By default, the system language should be used. If the locale file doesn't exists, then the default locale is the first language `<locale>` value defined by the user.

Currently the `properties` and `po` file format are supported. But in the future we can support `.yaml`, etc...

`en_US.properties`:

```
en_US = English
es_ES = Español
helloworld = Hello World
helloworldto = Hello World, {0}
insertyourname = Insert your name...
```

OR `en_US.po`:

```
msgid = "en_US"
msgstr = "English"

msgid = "es_ES"
msgstr = "Español"

msgid = "helloworld"
msgstr = "Hello World"

msgid = "helloworldto"
msgstr = "Hello World, {0}"

msgid = "insertyourname"
msgstr = "Insert your name..."
```

It supports params in runtime if you need it.

In the ui files, you need to use `_('ID')` in the property that you want to translate. If your text has parameters (in the form {0}, {1}, ...), then you can use `_('ID', param0, param1, ...)`.

Also, you can use properties from other components to set the locale string. For example `_('ID', component.text)`. If the param changes then the locale string changes too in runtime (thanks to binding system).

Example:

```
<vbox id="main">
    <style source="../css/main.css" />

    <script>
        function onLanguageChange() {
            LocaleManager.instance.setLanguage(languageSelector.selectedItem.localeID);
        }
    </script>

    <dropdown id="languageSelector"
              requireSelection="true"
              onchange="onLanguageChange()">
        <data>
            <item value="_('en_US')" localeID="en_US"/>
            <item value="_('es_ES')" localeID="es_ES"/>
        </data>
    </dropdown>

    <spacer height="20"/>

    <label text="_('helloworld')"/>
    <label text="_('helloworldto', 20)"/>
    <label text="_('helloworldto', 'Pablo')"/>
    <label text="_('helloworldto', true)"/>

    <spacer height="20"/>

    <textfield id="nameInput" placeholder="_('insertyourname')"/>
    <label text="_('helloworldto', nameInput.text)"/>

</vbox>
```

If you want to use that in Haxe code, you can use:

```
	var localeString:String = haxe.ui.locale.LocaleManager.get("LOCALE_ID", [param1, param2, ...]);
```

You can change the locale in runtime, and all texts will be changed (in your ui.xml, ui.json or ui.yaml files):

```
	haxe.ui.locale.LocaleManager.setLanguage('es_ES');
```

If you want to listen changes in Haxe code when the language is changed:

```
	function updateTexts() {
		component1.text = haxe.ui.locale.LocaleManager.get("LOCALE_ID_COMPONENT1");
	}

	haxe.ui.locale.LocaleManager.registerEvent(UIEvent.CHANGE, function(_){
		updateTexts();
	});

	updateTexts();
```

Also you can register/unregister languages in runtime:

```
	haxe.ui.locale.LocaleManager.registerLanguage("de_DE", [
		"LOCALE_ID_COMPONENT1" => "My component1"
	]);

	haxe.ui.locale.LocaleManager.unregisterLanguage("de_DE");
```

Feedback welcome.

### CODE REVIEW

**Comment by MSGhero** [comment]
Feedback: this is really neat :)

Is there some way in the backends to default to the system language? Or would that have to be something the user adds later?

**Comment by aW4KeNiNG** [comment]
It is defined by the user with the first language in the `module.xml`. Also it could be setted with `setLanguage` function after the `Toolkit.init()`.

**Comment by aW4KeNiNG** [comment]
Implemented the @MSGhero suggestion.

**Comment by aW4KeNiNG** [comment]
The example has been updated with Slider value bindable + Dialogs (the buttons are locales too).

**Comment by sh-dave** [comment]
Just found this while investigating on how to localize stuff in haxeui. Is this likely going to be merged at some point?

**Comment by ianharrigan** [comment]
Yeah, its a nice idea for sure - i wonder why it wasnt merged ages ago... It conflicts at the moment, so ill have to resolve that first.

**Pull request closed without merging**
