### PR TITLE
Fix locale2

### PR DESCRIPTION
**Pull request by Shallowmallow**

### CODE REVIEW

**Comment by ianharrigan** [comment]
whats the rationale behind removing the {{ }} stuff?

**Comment by Shallowmallow** [comment]
It's actually never used. You remove all the stuff before, so it doesn't happen. And _ I think_ also that if you force feed some it would never attain this part ( but I need to recheck this, I'm saying this by memory)

**Comment by ianharrigan** [comment]
you sure? https://haxeui.org/builder/?d30d3384

```xml
<button text="{{messagebox.title.info}} and {{messagebox.title.question}} and {{messagebox.title.warning}}" />
```

**Comment by ianharrigan** [comment]
oh, hang on, thats not what that code is doing... its allowing you to use locale strings _in_ local strings...

**Comment by Shallowmallow** [comment]
Oh... so yeah I can un remove it.... Can you give an example?  ( not 100% sure what it means)

**Comment by ianharrigan** [comment]
https://haxeui.org/builder/?949fe0fc

**Comment by Shallowmallow** [comment]
Oh yeah...  reverting this commit :)

**Comment by Shallowmallow** [comment]
And you actually had a nice comment... But yeah didn't really understand it. That's why I removed it... wanted to test the code without and nothing bad was happening...

**Pull request merged**
