### PR TITLE
[WIP] Css units: rem, vh, vw

### PR DESCRIPTION
**Pull request by aW4KeNiNG**
Hi.

I have added new css units:

* rem: based in a global unit. In html it should be the `font-size` global value. Here it is in `Toolkit.pixelsPerRem` (by default 16).

* vh & vw: based in the viewport size. 

Currently it works with OpenFL and my own mobile app.

Also all objects are updated when the viewport size or the `Toolkit.pixelsPerRem` value are changed.

In my own application, i change the `Toolkit.pixelsPerRem` value depending on the DPI value. I work in the desktop version with a fixed DPI (96) or fixed size. At startup then i calculate the new `Toolkit.pixelsPerRem` value when the DPI or the viewport size is different. So you can have PX values without scale and REM values scaled.

Issues
-----

I need help to fix a couple of issues:

1. In `Parser.hx`:
```
throw "Invalid char " + c0;//String.fromCharCode(c0);   //FIXME Error. s : String -> haxe.ui.util.VariantType has no field fromCharCode
```

2. In `Layout.hx`:

```
-        if (component.style.paddingBottom != null) padding += component.style.paddingBottom;	
+        if (component.style.paddingBottom != null) padding = component.style.paddingBottom + padding;
```
The error is `haxe.ui.util.Variant should be Float`. The implicit cast doesn't work.
All code in the form A += B or A -= B doesn't work with Variant. I have tried @:op without successful. It gives the same error with other backends (for example Kha). So i think we need a solution in the Variant code to avoid changes the backends.

Also, this doesn't work neither:

```
if (component.style.paddingBottom != null) padding = padding + component.style.paddingBottom;
```

The implicit cast again. Am i missing something?

Test
----

Here a test example:

haxeui

```
<?xml version="1.0" encoding="utf-8"?>
<vbox id="main" width="100%" height="100%">
    <!-- by default 1rem = 16px -->

    <button id="button1" text="Button1 1rem" 
        style="width: 200px; height:auto; font-size: 1rem;"  />
    <button id="button1" text="Button1 16px" 
        style="width: 200px; font-size: 16px;"  />
    <button id="button2" text="Button2 0.5rem" 
        style="width: 300px; font-size: 0.5rem;" />
    <button id="button2" text="Button2 8px" 
        style="width: 300px; font-size: 8px;" />

    <hbox>
        <button id="button3" text="Button3 2rem" 
            style="width: 20rem; font-size: 2rem;" />
        <button id="button3" text="Button3 32px" 
            style="width: 20rem; font-size: 32px;" />
    </hbox>
    
    <button id="button4" text="Button4 25vw 10vh" 
        style="width: 25vw; height: 10vh;" />
    <button id="button5" text="Button5 50vw 5vh" 
        style="width: 50vw; height: 5vh;" />
    <button id="button6" text="Button6 75vw 15vh" 
        style="width: 75vw; height: 15vh;" />
    <button id="button7" text="Button7 100vw 8vh" 
        style="width: 100vw; height: 8vh;" />

    <label text="Label1 2rem" style="font-size: 2rem;"/>
    <label text="Label1 32px" style="font-size: 32px"/>
    <label text="Label2 0.5rem" style="font-size: 0.5rem;"/>
    <label text="Label2 8px" style="font-size: 8px;"/>
    <label text="Label3 0.625rem" style="font-size: 0.625rem;"/>
    <label text="Label3 10px" style="font-size: 10px;"/>

</vbox>
```

The example works with:
- [x] OpenFL
- [x] HTML5
- [x] nme
- [x] hxWidgets
- [ ] PixiJS (partially, the style doesn't updated when the viewport change)
- [ ] Flambe (issue 2)
- [x] Kha (issue 2)
- [ ] Luxe (not tested yet)
- [x] XWT (rem ok, vh & vw with issues)

### CODE REVIEW

**Comment by aW4KeNiNG** [comment]
I have added the test result for each backend in the first post.

**Comment by ibilon** [comment]
snapshot6

This is the result on haxeui-xwt, some issues could be coming from the backend (for instance I had to remove `width="100%" height="100%"` from the main vbox otherwise it didn't work at all)

Rem seems to work fine,
but not vh/vh, could be related to the change in size of the main vbox but the result is the same when specifying a specific size in px.

**Comment by ianharrigan** [comment]
OK, this is really interesting... Nice one on the checklist of where it does (and doesnt work)

**Comment by ianharrigan** [comment]
What does "second error" mean?

**Comment by aW4KeNiNG** [comment]
Check the Issue 2 (it has numbers now).

**Comment by ianharrigan** [comment]
The variant issue should be fixed now, its in master and also a pr/css-units branch

**Comment by ianharrigan** [comment]
@ibilon - i think maybe the vh / vw isnt working because screen isnt returning the right values for screen width / height?

**Comment by ibilon** [comment]
> @ibilon - i think maybe the vh / vw isnt working because screen isnt returning the right values for screen width / height?

oh yeah that's right, fixed it and now it works (beside the 100% width/height of the vbox but that's a haxui-xwt issue)

**Comment by ianharrigan** [comment]
Can we get a screen shot and update the checklist? (im checking kha now)

**Comment by ibilon** [comment]
snapshot7

**Comment by ianharrigan** [comment]
Kha: 

image

**Comment by ianharrigan** [comment]
@aW4KeNiNG : ive invited you to be a member of the haxeui org... access to master branch is restricted, but you should be able to create your own branches and work from them, which will make merging and testing a little simpler. :)

**Comment by aW4KeNiNG** [comment]
Thanks @ianharrigan =)

**Pull request merged**
