### PR TITLE
Add flixel to readme

### PR DESCRIPTION
**Pull request by MSGhero**

### CODE REVIEW

**Comment by ianharrigan** [comment]
What is the state of this backend? Is it usable?

**Comment by MSGhero** [comment]
It's usable if you comment out the `color` style line in Component, #140. Flixel itself lacks click, wheel, and move "mouse events," but I have a PR to add those.

**Comment by ianharrigan** [comment]
Ah ok, well, we need think of something there then.

**Comment by Gama11** [comment]
1.5 years later, should it be added to the overview now? :)

**Comment by MSGhero** [comment]
:)

**Pull request merged**
