### PR TITLE
JustifyComponent for simple hboxes

### PR DESCRIPTION
**Pull request by Shallowmallow**
JustifyComponent for simple hboxes :)

### CODE REVIEW

**Comment by Shallowmallow** [comment]
image

**Comment by ianharrigan** [comment]
Ill merge this shortly, just want to fix all the CI actions so we have build confidence... i think this can also be done for vboxes, right? I wonder if it would work for grids also

**Comment by Shallowmallow** [comment]
Logically, it could be done also for vboxes. Hmm, for grids I'll have to draw it on paper to imagine it.

**Comment by ianharrigan** [comment]
thanks! :)

**Comment by Shallowmallow** [comment]
You're welcome  :)
Argh at the same minute I merged your commits  into my branch ( instead of
rebasing them, I was on the web UI and it wasn't clear) so now you a have
an ugly commit Merge branch 'haxeui:master' into master
<https://github.com/Shallowmallow/haxeui-core/commit/b02affca1d2f3d6e17421c9972bda17a6583747e>
Now I'm going to make branches for  the every change  ...

Le ven. 19 mai 2023 à 10:52, Ian Harrigan ***@***.***> a
écrit :

**Pull request merged**
