### PR TITLE
Update TableView.hx

### PR DESCRIPTION
**Pull request by hoseyjoe**
This fixes https://github.com/haxeui/haxeui-heaps/issues/30

It may not be best approach as other targets don't have the issue?

### CODE REVIEW

**Comment by hoseyjoe** [comment]
Line 460 needed it to  
var existing = item.findComponent(column.id, Component, true);

**Comment by ianharrigan** [comment]
Can we `#if haxe_heaps` it so its obvious its a haxeui heaps issue? ItemRenderer i think is the right choice here, so it may be that HL (or something) doesnt work there

**Comment by hoseyjoe** [comment]
We could "target specific" the code. My guess is that there is an issue higher up the food chain. HaxeUI Heaps has some peculiarities I don't see in other targets.

This fix doesn't hurt other targets that I am aware of

**Comment by hoseyjoe** [comment]
I believe it runs to heaps-js without change.  I am now getting the below error when compiling that project. I had to jam through a null check/reset value if null to ""
```
Uncaught TypeError: Cannot read properties of null (reading 'length')
    at h2d_TextInput.set_text (TextInput.hx:353)
    at haxe_ui_core_TextInput.validateData (TextDisplayImpl.hx:17)
    at haxe_ui_core_TextInput.validateComponentInternal (TextInput.hx:354)
    at haxe_ui_core_TextInput.validateComponent (TextInput.hx:336)
    at haxe_ui_components_TextArea.validateComponentInternal (ComponentValidation.hx:262)
    at haxe_ui_components_TextArea.validateComponentInternal (TextArea.hx:55)
    at haxe_ui_components_TextArea.validateComponent (ComponentValidation.hx:177)
    at haxe_ui_validation_ValidationManager.process (ValidationManager.hx:128)
    at haxe_ui_util_Timer.callback (Timer.hx:10)
    at Function.haxe_ui_backend_TimerImpl.update (TimerImpl.hx:13)
```

**Comment by hoseyjoe** [comment]
This was fixed with https://github.com/haxeui/haxeui-core/pull/413

**Pull request closed without merging**
