### PR TITLE
Find components in inactive TabView tabs.

### PR DESCRIPTION
**Pull request by bendmorris**
Currently findComponent on a TabView will only search the active tab. This PR searches all tabs if a component isn't found in the active tab.

### CODE REVIEW

**Comment by ianharrigan** [comment]
oh... very nice little PR...

**Comment by MSGhero** [comment]
Oh nice, I just now ran into this issue.

**Comment by MSGhero** [comment]
Actually... @bendmorris what if the component you're looking for *is* an inactive tab. You're checking the active tab's children, then the inactive tabs' children, but never the inactive tabs themselves, right?

**Comment by bendmorris** [comment]
I think you're right, if you're looking specifically for an inactive tab this wouldn't find it. Feel free to open another PR for that :stuck_out_tongue: 

You need the `super` to search parts of the TabView that aren't the tabs themselves, such as the TabBar and its children.

**Pull request merged**
